# GitHub Dependabot configuration for SOLO by Legalight
# Automates dependency updates across frontend, backend, and marketing

version: 2
updates:
  # Frontend React App Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "viesevieva5"  # Replace with actual GitHub username
    assignees:
      - "viesevieva5"  # Replace with actual GitHub username
    commit-message:
      prefix: "feat(frontend)"
      include: "scope"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      testing-libraries:
        patterns:
          - "@testing-library/*"
          - "jest*"
      ui-components:
        patterns:
          - "@headlessui/*"
          - "@heroicons/*"
          - "lucide-react"
          - "framer-motion"
      build-tools:
        patterns:
          - "typescript"
          - "tailwindcss"
          - "autoprefixer"
          - "postcss"
    ignore:
      # Pin React Scripts to avoid breaking changes
      - dependency-name: "react-scripts"
        update-types: ["version-update:semver-major"]
      # Pin React 19 - only allow patch updates for now  
      - dependency-name: "react"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Marketing Site (Next.js) Dependencies  
  - package-ecosystem: "npm"
    directory: "/marketing"
    schedule:
      interval: "weekly"  
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    reviewers:
      - "viesevieva5"  # Replace with actual GitHub username
    assignees:
      - "viesevieva5"  # Replace with actual GitHub username
    commit-message:
      prefix: "feat(marketing)"
      include: "scope"
    groups:
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      form-handling:
        patterns:
          - "react-hook-form"
          - "@hookform/*"
          - "zod"
      build-tools:
        patterns:
          - "typescript"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "eslint*"
          - "prettier*"

  # Security Updates (High Priority)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "viesevieva5"  # Replace with actual GitHub username
    assignees:
      - "viesevieva5"  # Replace with actual GitHub username
    commit-message:
      prefix: "security"
      include: "scope"
    # Only security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect" 
        update-type: "security"

  # Security Updates for Marketing
  - package-ecosystem: "npm"
    directory: "/marketing"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "viesevieva5"  # Replace with actual GitHub username
    assignees:
      - "viesevieva5"  # Replace with actual GitHub username
    commit-message:
      prefix: "security(marketing)"
      include: "scope"
    # Only security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"